name = "agan-chatbot"
compatibility_date = "2024-01-01"

[env.production]
vars = {}

[[env.production.kv_namespaces]]
binding = "CHAT_KV"
id = "your_kv_namespace_id"

[build]
command = "npm run build"
cwd = ""
watch_dir = ""
